# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Project Tapestry: Technology"
email: contact@thealliance.ai
description: >- # this means to ignore newlines until "baseurl:"
  The technical website for Project Tapestry.
baseurl: "/tapestry" # the subpath of your site.
url: "https://the-ai-alliance.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "Makefile"
, "website/tests/", "notes.md", "vendor"
]

# Added by AI Alliance: our glossary URL and the main tapestry page URL.
glossaryurl: https://the-ai-alliance.github.io/glossary
tapestryurl: https://thealliance.ai/projects/tapestry

# Regression tests
# By default, the pages in /website/tests are excluded when the site is built.
# To include them, comment-out the relevant line above.
# Uncommenting the following line doesn't work - see https://github.com/jekyll/jekyll/issues/4791
# include: ["website/tests/"]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 6
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "The AI Alliance":
    - "https://www.thealliance.ai"

nav_external_links:
  - title: "The AI Alliance technical repo for Project Tapestry"
    url: "https://github.com/The-AI-Alliance/tapestry"
    hide_icon: false

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# For copy button on code
enable_copy_code_button: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to the top"

# Whether or not to show some footer information and where (Added by AIA team). 
# "show_footer" determines if the primary footer content like the version,
# timestamp and "edit this page" appear at the bottom of the "main" content,
# before the copyright in the side bar, both places, or neither place. 
# Use one of these values:
#   side_bar  Show in the side bar above the copyright, etc.
#   main      Show the main content footer. Unlike for side bar rendering, 
#             if not shown in the main content, NO footer content is shown
#             here, including the built-in support for a custom footer include file.
#             You can change this behavior by editing _layout/default.html...
#   both      Show in both places.
#   ""        Don't show this content in either place. (Also suppresses main footer...)
show_footer: side_bar
# show_footer: main
# show_footer: both
# show_footer: 

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%Y-%m-%d" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
last_modified_date: 2026-06-22
last_version: V0.1.3

# Custom: Add the range of years for the copyright here. This is done here,
# rather than default.html, so that the latter file can remain completely 
# generic across repos, but the range of years can be configurable per repo.
copyright_years: 2025-2026

# "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/The-AI-Alliance/tapestry" # the github URL for your repo
gh_edit_branch: "develop" # the branch that your docs are served from
gh_edit_source: "website" # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-RNHLN944B5
#ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-target-blank
  - jemoji

kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  # version: "9.1.5"

